Team302/2025Reefscape

.wpilib/wpilib_preferences.json
src/main/cpp/chassis/TractionControlController.h
src/main/cpp/chassis/driveStates/DriveToNote.cpp
src/main/cpp/gamepad/axis/CubedProfile.cpp
src/main/cpp/state/StateMgr.cpp
src/main/cpp/teleopcontrol/TeleopControl.cpp
src/main/cpp/utils/AngleUtils.cpp
src/main/cpp/utils/logging/LoggableItemMgr.cpp
src/main/cpp/vision/DragonVision.cpp
src/main/deploy/chassis/swervemodule_9997.xml
src/main/thirdparty/elasticlib/elasticlib.cpp
src/main/thirdparty/elasticlib/elasticlib.h

- added a fix for dragon vision crash
- removed namespace declarations that were not used
- updated 9997 swerve config
- added elasticlib includes

Dragon vision crash fix

---

src/main/cpp/feedback/DriverFeedback.cpp
src/main/cpp/feedback/DriverFeedback.h
src/main/cpp/state/RobotState.cpp
src/main/cpp/state/RobotState.h
src/main/cpp/state/RobotStateChanges.h
src/main/cpp/teleopcontrol/TeleopControlFunctions.h

1. Updated scoring mode enum to have coral and algae
2. added climbmode publisher to robotstate and updated scoringmode publisher to be algae and coral
3. updated UpdateLEDStates() for climbmode and coral/algae
👍

Updated Robot States/feedback

---

src/main/cpp/utils/InterpolateUtils.cpp
src/main/cpp/utils/InterpolateUtils.h

Added table interpolation (linear) as a utility class. 
Use Cases:
1.  PID for different value for different errors
2. Target functions (Rather than a polynomial for launcher angle for example you can use a table)
3. Anything else you need to interpolate for

Added Interpolate Table value untils

---

src/main/cpp/vision/DragonLimelight.cpp
src/main/cpp/vision/DragonLimelight.h

I did software stuff to include the three basics in to usage.

I did the limelight to include usage

---

src/main/cpp/Robot.cpp
src/main/cpp/SensorData.cpp
src/main/cpp/SensorData.h
src/main/cpp/SensorDataMgr.cpp
src/main/cpp/SensorDataMgr.h
src/main/cpp/vision/DragonLimelight.cpp
src/main/cpp/vision/DragonLimelight.h

Please be no requested changes unless there are

8 implement caching of the limelight data

---

src/main/cpp/feedback/DriverFeedback.cpp
src/main/cpp/state/IRobotStateChangeSubscriber.h
src/main/cpp/state/RobotState.cpp
src/main/cpp/state/RobotState.h
src/main/cpp/state/RobotStateChangeBroker.cpp
src/main/cpp/state/RobotStateChangeBroker.h
src/main/cpp/state/RobotStateChanges.h

98 update robotstatechangebrokerclass to handle different types of variables

---

src/main/cpp/mechanisms/DragonTale/ScoreAlgaeState.cpp
src/main/cpp/mechanisms/DragonTale/ScoreCoralState.cpp

Updates IsTransitionCondition for Score Coral State Also updates IsTransitionCondition for Score Algae State

Update transition condition

---

src/main/cpp/mechanisms/DragonTale/DragonTale.h

made settarget methods

---

src/main/cpp/state/RobotState.cpp

Finished updating scoring mode to algae if elevator state is GrabAlgaeReefState

Finish scoring mode upd if our elevator state is grabalgaereef

---

src/main/cpp/mechanisms/DragonTale/HumanPlayerLoadState.cpp

124 elevatorarm mech update istransitioncondition for humanplayerload state

---

src/main/cpp/vision/DragonCamera.cpp
src/main/cpp/vision/DragonCamera.h
src/main/cpp/vision/DragonLimelight.cpp
src/main/cpp/vision/DragonLimelight.h
src/main/cpp/vision/definitions/CameraConfig_9997.cpp
src/main/thirdparty/Limelight/LimelightHelpers.h

Update dragon camera to add usage and type
Update limelight helpers
Update dragonlimelight to user the helpers
Closes #151

Add dragon vision usage, type

---

build.gradle
src/main/cpp/auton/drivePrimitives/ResetPositionPathPlanner.cpp
src/main/cpp/fielddata/FieldConstants.cpp
src/main/cpp/fielddata/FieldConstantsPoseLogger.cpp
src/main/cpp/fielddata/FieldConstantsPoseLogger.h
src/main/cpp/fielddata/FieldElementCalculator.cpp
src/main/cpp/fielddata/FieldElementCalculator.h

closes #250, closes #249 , closes #254
Fixed center not working, validated all positions in advantage scope

250 update field constants to calculate csa locations

---

.github/workflows/xml-validation.yml
src/main/deploy/9999/mechanisms/ClimberManager.xml
src/main/deploy/9999/mechanisms/DragonTale.xml
src/main/deploy/9999/mechanisms/IntakeManager.xml
src/main/deploy/9999/mechanisms/mechanisms.dtd
src/main/deploy/auton/snippets/PodiumStart.xml
src/main/deploy/auton/snippets/PodiumWingRing3.xml
src/main/deploy/chassis/chassis.dtd
src/main/deploy/chassis/swervechassis_302.xml
src/main/deploy/chassis/swervechassis_9997.xml
src/main/deploy/chassis/swervechassis_9998.xml
src/main/deploy/chassis/swervemodule_302.xml
src/main/deploy/chassis/swervemodule_9997.xml
src/main/deploy/chassis/swervemodule_9998.xml
src/main/deploy/robot.xml

added xml validation workflow for all xmls

Xml validation

---

src/main/cpp/chassis/states/FaceNearestCoralStation.cpp
src/main/cpp/chassis/states/FaceNearestCoralStation.h
src/main/cpp/chassis/states/FaceNearestReefFace.cpp
src/main/cpp/chassis/states/FaceNearestReefFace.h
src/main/cpp/chassis/states/FaceReefCenter.h

There were some unneeded angle functions in these new classes that were not needed. Remove them. 
Closes #325

remove unneeded angles from #322

---

src/main/cpp/auton/ZoneParams.cpp
src/main/cpp/chassis/DragonSwervePoseEstimator.cpp
src/main/cpp/chassis/HolonomicDrive.cpp
src/main/cpp/chassis/SwerveChassis.cpp
src/main/cpp/chassis/SwerveChassis.h
src/main/cpp/chassis/states/FieldDrive.cpp
src/main/cpp/chassis/states/RobotDrive.cpp

Fix loop overruns in chassis code

---

src/main/cpp/RobotIdentifier.h
src/main/cpp/auton/AutonSelector.cpp
src/main/cpp/chassis/definitions/ChassisConfigMgr.cpp
src/main/cpp/configs/MechanismConfigMgr.cpp
src/main/cpp/feedback/LEDStates.cpp
src/main/cpp/fielddata/FieldConstantsPoseLogger.cpp
src/main/cpp/fielddata/FieldElementCalculator.cpp
src/main/cpp/utils/logging/DragonDataLoggerMgr.cpp
src/main/cpp/vision/definitions/CameraConfigMgr.cpp
src/main/cpp/vision/definitions/CameraConfig_9999.cpp
src/main/cpp/vision/definitions/CameraConfig_9999.h
src/main/thirdparty/Limelight/LimelightHelpers.h

fixed the code so that it works with robot simulation. Added some ifdefs to confirm that the regular build and desktop build both work with no changes required other than compiling for each platform

fix desktop sim and added simbot0

---

src/main/cpp/chassis/SwerveChassis.cpp
src/main/cpp/chassis/states/DriveToRightReefBranch.cpp
src/main/cpp/chassis/states/DriveToRightReefBranch.h

94 - added driveToRightReefBranch

---

src/main/cpp/vision/DragonLimelight.cpp
src/main/cpp/vision/DragonVision.cpp

- Make quick accessor methods multi-camera aware

Updates for DragonVision

---

src/main/cpp/vision/definitions/CameraConfigMgr.cpp
src/main/cpp/vision/definitions/CameraConfig_9997.cpp
src/main/cpp/vision/definitions/CameraConfig_9998.cpp
src/main/cpp/vision/definitions/CameraConfig_9998.h

This adds the camera to 9998 so that others can test on it

add 9998 camera

---

src/main/cpp/vision/definitions/CameraConfigMgr.cpp
src/main/cpp/vision/definitions/CameraConfig_302.cpp
src/main/cpp/vision/definitions/CameraConfig_302.h

Added front limelight camera to comp bot

add comp bot cameras

---

src/main/cpp/Robot.cpp
src/main/cpp/fielddata/FieldElementCalculator.cpp
src/main/cpp/fielddata/FieldElementCalculator.h

added robot specific offsets for each robot and it's transform to left and right stick separate from the right and left stick.
Also initialized fieldConstants to calculate these values as part of robot init as this may not have been calculated soon enough before.

Added reefstick offsets

---

src/main/cpp/fielddata/FieldElementCalculator.cpp
src/main/cpp/fielddata/FieldElementCalculator.h

Adding new reefbranch offsets

---

src/main/cpp/vision/DragonQuest.cpp

this fixes desktop sim since windows doesn't know what it means to sleep.

fix-desktop-sim

---

src/main/cpp/chassis/states/DriveToFieldElement.cpp
src/main/cpp/chassis/states/DriveToFieldElement.h

Added if we aren't moving then say we are done, may want to tune the value for how long we wait. Currently set to 0.5 sec. It might be too fast, we may need to increase it or tune out gains better so we get closer to out end spot.

Drive to is done update

---

build.gradle
src/main/cpp/feedback/DragonLeds.cpp
src/main/cpp/feedback/DragonLeds.h
src/main/cpp/feedback/DriverFeedback.cpp
src/main/cpp/feedback/DriverFeedback.h

removes some leds to match what is now on the robot, for clarity for the pit crew.

Fixed LEDs part 4

---

src/main/cpp/feedback/DriverFeedback.cpp
src/main/cpp/feedback/DriverFeedback.h

rumbles the copilot when driveto is finished

Rumble copilot

---

src/main/cpp/fielddata/FieldElementCalculator.cpp
src/main/cpp/fielddata/FieldElementCalculator.h

added reef branch constants

---

src/main/cpp/chassis/HolonomicDrive.cpp
src/main/cpp/fielddata/FieldElementCalculator.h
src/main/cpp/mechanisms/DragonTale/DragonTale.cpp
src/main/cpp/mechanisms/DragonTale/DragonTale.h
src/main/cpp/mechanisms/DragonTale/GrabAlgaeFloorState.h
src/main/cpp/mechanisms/DragonTale/HumanPlayerLoadState.h
src/main/cpp/mechanisms/DragonTale/L2ScoringPositionState.cpp
src/main/cpp/mechanisms/DragonTale/L2ScoringPositionState.h
src/main/cpp/mechanisms/DragonTale/L3ScoringPositionState.h
src/main/cpp/mechanisms/DragonTale/L4ScoringPositionState.cpp
src/main/cpp/mechanisms/DragonTale/L4ScoringPositionState.h
src/main/cpp/mechanisms/DragonTale/ReadyState.h
src/main/cpp/mechanisms/DragonTale/ScoreCoralState.cpp
src/main/cpp/state/RobotStateChanges.h
src/main/cpp/vision/DragonQuest.cpp
src/main/cpp/vision/DragonQuest.h
src/main/deploy/302/mechanisms/DragonTale.xml
src/main/deploy/auton/L4/BlueCenterGHCoralL4.xml
src/main/deploy/auton/L4/BlueLeftILCoralL4.xml
src/main/deploy/auton/L4/BlueRightCFCoralL4.xml
src/main/deploy/auton/L4/RedCenterGHCoralL4.xml
src/main/deploy/auton/L4/RedLeftILCoralL4.xml
src/main/deploy/auton/L4/RedRightCFCoralL4.xml

Should leave it open, might want to check blue and red tomorrow and verify it all works still. Sadly had to add  a small delay

Rainbow rumble drive practice
